version: '3'

services:
  fastapi-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10-2023-09-11
    container_name: spacelog-container
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
